import jsPDF from 'jspdf';

export async function generateCalculatorPDF(
  calculatorSlug: string,
  data: Record<string, unknown>,
  results: Record<string, unknown>
): Promise<void> {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Calculator Results', 20, 20);
  
  // Calculator name
  doc.setFontSize(14);
  doc.text(calculatorSlug.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase()), 20, 35);
  
  // Date
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 45);
  
  // Inputs
  doc.setFontSize(12);
  doc.text('Inputs:', 20, 60);
  let y = 70;
  Object.entries(data).forEach(([key, value]) => {
    doc.setFontSize(10);
    doc.text(`${key}: ${value}`, 25, y);
    y += 8;
  });
  
  // Results
  y += 10;
  doc.setFontSize(12);
  doc.text('Results:', 20, y);
  y += 10;
  Object.entries(results).forEach(([key, value]) => {
    if (key !== 'isValid' && typeof value !== 'object') {
      doc.setFontSize(10);
      doc.text(`${key}: ${value}`, 25, y);
      y += 8;
    }
  });
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by Kalcufy - https://www.kalcufy.com', 20, 280);
  
  // Save
  doc.save(`${calculatorSlug}-results.pdf`);
}
