import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const blogPosts = [
  { slugEn: "compound-interest-guide", slugEs: "guia-interes-compuesto", slugPt: "guia-juros-compostos", titleEn: "Compound Interest Guide", titleEs: "Guia de Interes Compuesto", titlePt: "Guia de Juros Compostos", excerptEn: "Learn how compound interest works.", excerptEs: "Aprende como funciona el interes compuesto.", excerptPt: "Aprenda como funcionam os juros compostos.", contentEn: "Compound interest is interest on interest. Your money grows exponentially. Use our calculator!", contentEs: "El interes compuesto es interes sobre interes. Tu dinero crece exponencialmente. Usa nuestra calculadora!", contentPt: "Juros compostos sao juros sobre juros. Seu dinheiro cresce exponencialmente. Use nossa calculadora!", relatedCalculator: "compound-interest-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "mortgage-guide", slugEs: "guia-hipoteca", slugPt: "guia-hipoteca", titleEn: "Mortgage Guide", titleEs: "Guia de Hipoteca", titlePt: "Guia de Hipoteca", excerptEn: "Everything about mortgages.", excerptEs: "Todo sobre hipotecas.", excerptPt: "Tudo sobre hipotecas.", contentEn: "A mortgage is a loan to buy property. Use our calculator!", contentEs: "Una hipoteca es un prestamo para comprar propiedad. Usa nuestra calculadora!", contentPt: "Uma hipoteca e um emprestimo para comprar propriedade. Use nossa calculadora!", relatedCalculator: "mortgage-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "loan-guide", slugEs: "guia-prestamo", slugPt: "guia-emprestimo", titleEn: "Personal Loan Guide", titleEs: "Guia de Prestamo Personal", titlePt: "Guia de Emprestimo Pessoal", excerptEn: "Learn about personal loans.", excerptEs: "Aprende sobre prestamos personales.", excerptPt: "Aprenda sobre emprestimos pessoais.", contentEn: "Personal loans are unsecured loans for any purpose. Use our calculator!", contentEs: "Los prestamos personales son sin garantia para cualquier proposito. Usa nuestra calculadora!", contentPt: "Emprestimos pessoais sao sem garantia para qualquer finalidade. Use nossa calculadora!", relatedCalculator: "loan-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "auto-loan-guide", slugEs: "guia-prestamo-auto", slugPt: "guia-emprestimo-auto", titleEn: "Auto Loan Guide", titleEs: "Guia de Prestamo de Auto", titlePt: "Guia de Emprestimo de Carro", excerptEn: "Get the best auto loan rates.", excerptEs: "Obten las mejores tasas de prestamo de auto.", excerptPt: "Obtenha as melhores taxas de emprestimo de carro.", contentEn: "Auto loans use your car as collateral. Use our calculator!", contentEs: "Los prestamos de auto usan tu carro como garantia. Usa nuestra calculadora!", contentPt: "Emprestimos de carro usam seu carro como garantia. Use nossa calculadora!", relatedCalculator: "auto-loan-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "retirement-guide", slugEs: "guia-jubilacion", slugPt: "guia-aposentadoria", titleEn: "Retirement Planning Guide", titleEs: "Guia de Planificacion del Retiro", titlePt: "Guia de Planejamento de Aposentadoria", excerptEn: "Plan your retirement.", excerptEs: "Planifica tu retiro.", excerptPt: "Planeje sua aposentadoria.", contentEn: "Use the 25x rule for retirement planning. Use our calculator!", contentEs: "Usa la regla del 25x para planificar el retiro. Usa nuestra calculadora!", contentPt: "Use a regra dos 25x para planejar a aposentadoria. Use nossa calculadora!", relatedCalculator: "retirement-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "savings-guide", slugEs: "guia-ahorros", slugPt: "guia-poupanca", titleEn: "Savings Account Guide", titleEs: "Guia de Cuenta de Ahorros", titlePt: "Guia de Conta Poupanca", excerptEn: "Maximize your savings.", excerptEs: "Maximiza tus ahorros.", excerptPt: "Maximize suas economias.", contentEn: "Use high-yield savings accounts. Use our calculator!", contentEs: "Usa cuentas de ahorro de alto rendimiento. Usa nuestra calculadora!", contentPt: "Use contas poupanca de alto rendimento. Use nossa calculadora!", relatedCalculator: "savings-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "credit-card-payoff-guide", slugEs: "guia-pagar-tarjeta", slugPt: "guia-pagar-cartao", titleEn: "Credit Card Payoff Guide", titleEs: "Guia para Pagar Tarjeta de Credito", titlePt: "Guia para Pagar Cartao de Credito", excerptEn: "Pay off credit card debt.", excerptEs: "Paga tu deuda de tarjeta de credito.", excerptPt: "Pague sua divida de cartao de credito.", contentEn: "Use snowball or avalanche method. Use our calculator!", contentEs: "Usa el metodo bola de nieve o avalancha. Usa nuestra calculadora!", contentPt: "Use o metodo bola de neve ou avalanche. Use nossa calculadora!", relatedCalculator: "credit-card-payoff-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "401k-guide", slugEs: "guia-401k", slugPt: "guia-401k", titleEn: "401k Guide", titleEs: "Guia 401k", titlePt: "Guia 401k", excerptEn: "Maximize your 401k.", excerptEs: "Maximiza tu 401k.", excerptPt: "Maximize seu 401k.", contentEn: "Always get the full employer match. Use our calculator!", contentEs: "Siempre obten el match completo del empleador. Usa nuestra calculadora!", contentPt: "Sempre obtenha o match completo do empregador. Use nossa calculadora!", relatedCalculator: "401k-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "budget-guide", slugEs: "guia-presupuesto", slugPt: "guia-orcamento", titleEn: "Budget Guide", titleEs: "Guia de Presupuesto", titlePt: "Guia de Orcamento", excerptEn: "Create a budget.", excerptEs: "Crea un presupuesto.", excerptPt: "Crie um orcamento.", contentEn: "Use the 50/30/20 rule. Use our calculator!", contentEs: "Usa la regla 50/30/20. Usa nuestra calculadora!", contentPt: "Use a regra 50/30/20. Use nossa calculadora!", relatedCalculator: "budget-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "income-tax-guide", slugEs: "guia-impuestos", slugPt: "guia-impostos", titleEn: "Income Tax Guide", titleEs: "Guia de Impuestos", titlePt: "Guia de Impostos", excerptEn: "Understand your taxes.", excerptEs: "Entiende tus impuestos.", excerptPt: "Entenda seus impostos.", contentEn: "Know your tax bracket and deductions. Use our calculator!", contentEs: "Conoce tu tramo de impuestos y deducciones. Usa nuestra calculadora!", contentPt: "Conheca sua faixa de impostos e deducoes. Use nossa calculadora!", relatedCalculator: "income-tax-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "investment-guide", slugEs: "guia-inversiones", slugPt: "guia-investimentos", titleEn: "Investment Guide", titleEs: "Guia de Inversiones", titlePt: "Guia de Investimentos", excerptEn: "Start investing.", excerptEs: "Empieza a invertir.", excerptPt: "Comece a investir.", contentEn: "Diversify your investments. Use our calculator!", contentEs: "Diversifica tus inversiones. Usa nuestra calculadora!", contentPt: "Diversifique seus investimentos. Use nossa calculadora!", relatedCalculator: "investment-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "paycheck-guide", slugEs: "guia-cheque-pago", slugPt: "guia-contracheque", titleEn: "Paycheck Guide", titleEs: "Guia de Cheque de Pago", titlePt: "Guia de Contracheque", excerptEn: "Understand your paycheck.", excerptEs: "Entiende tu cheque de pago.", excerptPt: "Entenda seu contracheque.", contentEn: "Know your gross vs net pay. Use our calculator!", contentEs: "Conoce tu pago bruto vs neto. Usa nuestra calculadora!", contentPt: "Conheca seu salario bruto vs liquido. Use nossa calculadora!", relatedCalculator: "paycheck-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "personal-loan-guide", slugEs: "guia-prestamo-personal", slugPt: "guia-emprestimo-pessoal", titleEn: "Personal Loan Calculator Guide", titleEs: "Guia de Calculadora de Prestamo", titlePt: "Guia de Calculadora de Emprestimo", excerptEn: "Plan your loan.", excerptEs: "Planifica tu prestamo.", excerptPt: "Planeje seu emprestimo.", contentEn: "Compare rates and terms. Use our calculator!", contentEs: "Compara tasas y plazos. Usa nuestra calculadora!", contentPt: "Compare taxas e prazos. Use nossa calculadora!", relatedCalculator: "personal-loan-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "profit-margin-guide", slugEs: "guia-margen-ganancia", slugPt: "guia-margem-lucro", titleEn: "Profit Margin Guide", titleEs: "Guia de Margen de Ganancia", titlePt: "Guia de Margem de Lucro", excerptEn: "Calculate profit margins.", excerptEs: "Calcula margenes de ganancia.", excerptPt: "Calcule margens de lucro.", contentEn: "Understand gross, operating, and net margin. Use our calculator!", contentEs: "Entiende margen bruto, operativo y neto. Usa nuestra calculadora!", contentPt: "Entenda margem bruta, operacional e liquida. Use nossa calculadora!", relatedCalculator: "profit-margin-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "roth-ira-guide", slugEs: "guia-roth-ira", slugPt: "guia-roth-ira", titleEn: "Roth IRA Guide", titleEs: "Guia Roth IRA", titlePt: "Guia Roth IRA", excerptEn: "Tax-free retirement.", excerptEs: "Jubilacion libre de impuestos.", excerptPt: "Aposentadoria livre de impostos.", contentEn: "After-tax contributions, tax-free withdrawals. Use our calculator!", contentEs: "Contribuciones post-impuestos, retiros libres de impuestos. Usa nuestra calculadora!", contentPt: "Contribuicoes pos-impostos, saques livres de impostos. Use nossa calculadora!", relatedCalculator: "roth-ira-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "student-loan-guide", slugEs: "guia-prestamo-estudiantil", slugPt: "guia-emprestimo-estudantil", titleEn: "Student Loan Guide", titleEs: "Guia de Prestamo Estudiantil", titlePt: "Guia de Emprestimo Estudantil", excerptEn: "Manage student loans.", excerptEs: "Administra prestamos estudiantiles.", excerptPt: "Gerencie emprestimos estudantis.", contentEn: "Federal vs private loans. Use our calculator!", contentEs: "Prestamos federales vs privados. Usa nuestra calculadora!", contentPt: "Emprestimos federais vs privados. Use nossa calculadora!", relatedCalculator: "student-loan-calculator", tags: ["finance"], category: "finance", readingTime: 5 },
  { slugEn: "net-worth-guide", slugEs: "guia-patrimonio-neto", slugPt: "guia-patrimonio-liquido", titleEn: "Net Worth Guide", titleEs: "Guia de Patrimonio Neto", titlePt: "Guia de Patrimonio Liquido", excerptEn: "Track your net worth.", excerptEs: "Rastrea tu patrimonio neto.", excerptPt: "Rastreie seu patrimonio liquido.", contentEn: "Assets minus liabilities. Use our calculator!", contentEs: "Activos menos pasivos. Usa nuestra calculadora!", contentPt: "Ativos menos passivos. Use nossa calculadora!", relatedCalculator: "net-worth-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "emergency-fund-guide", slugEs: "guia-fondo-emergencia", slugPt: "guia-fundo-emergencia", titleEn: "Emergency Fund Guide", titleEs: "Guia de Fondo de Emergencia", titlePt: "Guia de Fundo de Emergencia", excerptEn: "Build your emergency fund.", excerptEs: "Construye tu fondo de emergencia.", excerptPt: "Construa seu fundo de emergencia.", contentEn: "Save 3-6 months of expenses. Use our calculator!", contentEs: "Ahorra 3-6 meses de gastos. Usa nuestra calculadora!", contentPt: "Economize 3-6 meses de despesas. Use nossa calculadora!", relatedCalculator: "emergency-fund-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "cd-guide", slugEs: "guia-cd", slugPt: "guia-cd", titleEn: "CD Guide", titleEs: "Guia de CD", titlePt: "Guia de CD", excerptEn: "Safe investment returns.", excerptEs: "Retornos de inversion seguros.", excerptPt: "Retornos de investimento seguros.", contentEn: "Fixed rate for fixed term. Use our calculator!", contentEs: "Tasa fija por plazo fijo. Usa nuestra calculadora!", contentPt: "Taxa fixa por prazo fixo. Use nossa calculadora!", relatedCalculator: "cd-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "car-lease-guide", slugEs: "guia-arrendamiento-auto", slugPt: "guia-leasing-carro", titleEn: "Car Lease Guide", titleEs: "Guia de Arrendamiento de Auto", titlePt: "Guia de Leasing de Carro", excerptEn: "Lease vs buy a car.", excerptEs: "Arrendar vs comprar un carro.", excerptPt: "Leasing vs comprar um carro.", contentEn: "Lower payments but no ownership. Use our calculator!", contentEs: "Pagos mas bajos pero sin propiedad. Usa nuestra calculadora!", contentPt: "Pagamentos mais baixos mas sem propriedade. Use nossa calculadora!", relatedCalculator: "car-lease-calculator", tags: ["finance"], category: "finance", readingTime: 4 },
  { slugEn: "bmi-guide", slugEs: "guia-imc", slugPt: "guia-imc", titleEn: "BMI Guide", titleEs: "Guia de IMC", titlePt: "Guia de IMC", excerptEn: "Understand BMI.", excerptEs: "Entiende el IMC.", excerptPt: "Entenda o IMC.", contentEn: "Weight divided by height squared. Use our calculator!", contentEs: "Peso dividido por altura al cuadrado. Usa nuestra calculadora!", contentPt: "Peso dividido pela altura ao quadrado. Use nossa calculadora!", relatedCalculator: "bmi-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "calorie-guide", slugEs: "guia-calorias", slugPt: "guia-calorias", titleEn: "Calorie Guide", titleEs: "Guia de Calorias", titlePt: "Guia de Calorias", excerptEn: "Calculate daily calories.", excerptEs: "Calcula calorias diarias.", excerptPt: "Calcule calorias diarias.", contentEn: "Based on age, weight, activity. Use our calculator!", contentEs: "Basado en edad, peso, actividad. Usa nuestra calculadora!", contentPt: "Baseado em idade, peso, atividade. Use nossa calculadora!", relatedCalculator: "calorie-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "bmr-guide", slugEs: "guia-tmb", slugPt: "guia-tmb", titleEn: "BMR Guide", titleEs: "Guia de TMB", titlePt: "Guia de TMB", excerptEn: "Understand metabolism.", excerptEs: "Entiende el metabolismo.", excerptPt: "Entenda o metabolismo.", contentEn: "Calories burned at rest. Use our calculator!", contentEs: "Calorias quemadas en reposo. Usa nuestra calculadora!", contentPt: "Calorias queimadas em repouso. Use nossa calculadora!", relatedCalculator: "bmr-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "tdee-guide", slugEs: "guia-gdte", slugPt: "guia-gdte", titleEn: "TDEE Guide", titleEs: "Guia de GDTE", titlePt: "Guia de GDTE", excerptEn: "Total daily energy.", excerptEs: "Gasto diario total de energia.", excerptPt: "Gasto diario total de energia.", contentEn: "BMR times activity factor. Use our calculator!", contentEs: "TMB por factor de actividad. Usa nuestra calculadora!", contentPt: "TMB vezes fator de atividade. Use nossa calculadora!", relatedCalculator: "tdee-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "body-fat-guide", slugEs: "guia-grasa-corporal", slugPt: "guia-gordura-corporal", titleEn: "Body Fat Guide", titleEs: "Guia de Grasa Corporal", titlePt: "Guia de Gordura Corporal", excerptEn: "Healthy body fat levels.", excerptEs: "Niveles saludables de grasa corporal.", excerptPt: "Niveis saudaveis de gordura corporal.", contentEn: "Different ranges for men and women. Use our calculator!", contentEs: "Diferentes rangos para hombres y mujeres. Usa nuestra calculadora!", contentPt: "Diferentes faixas para homens e mulheres. Use nossa calculadora!", relatedCalculator: "body-fat-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "macro-guide", slugEs: "guia-macros", slugPt: "guia-macros", titleEn: "Macro Guide", titleEs: "Guia de Macros", titlePt: "Guia de Macros", excerptEn: "Balance your macros.", excerptEs: "Equilibra tus macros.", excerptPt: "Equilibre seus macros.", contentEn: "Protein, carbs, and fat. Use our calculator!", contentEs: "Proteina, carbohidratos y grasa. Usa nuestra calculadora!", contentPt: "Proteina, carboidratos e gordura. Use nossa calculadora!", relatedCalculator: "macro-calculator", tags: ["health"], category: "health", readingTime: 5 },
  { slugEn: "ideal-weight-guide", slugEs: "guia-peso-ideal", slugPt: "guia-peso-ideal", titleEn: "Ideal Weight Guide", titleEs: "Guia de Peso Ideal", titlePt: "Guia de Peso Ideal", excerptEn: "Find your ideal weight.", excerptEs: "Encuentra tu peso ideal.", excerptPt: "Encontre seu peso ideal.", contentEn: "Multiple formulas available. Use our calculator!", contentEs: "Multiples formulas disponibles. Usa nuestra calculadora!", contentPt: "Multiplas formulas disponiveis. Use nossa calculadora!", relatedCalculator: "ideal-weight-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "protein-guide", slugEs: "guia-proteina", slugPt: "guia-proteina", titleEn: "Protein Guide", titleEs: "Guia de Proteina", titlePt: "Guia de Proteina", excerptEn: "Calculate protein needs.", excerptEs: "Calcula necesidades de proteina.", excerptPt: "Calcule necessidades de proteina.", contentEn: "Based on activity level. Use our calculator!", contentEs: "Basado en nivel de actividad. Usa nuestra calculadora!", contentPt: "Baseado em nivel de atividade. Use nossa calculadora!", relatedCalculator: "protein-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "water-intake-guide", slugEs: "guia-ingesta-agua", slugPt: "guia-ingestao-agua", titleEn: "Water Intake Guide", titleEs: "Guia de Ingesta de Agua", titlePt: "Guia de Ingestao de Agua", excerptEn: "Stay hydrated.", excerptEs: "Mantente hidratado.", excerptPt: "Mantenha-se hidratado.", contentEn: "About 3.7L for men, 2.7L for women. Use our calculator!", contentEs: "Alrededor de 3.7L para hombres, 2.7L para mujeres. Usa nuestra calculadora!", contentPt: "Cerca de 3.7L para homens, 2.7L para mulheres. Use nossa calculadora!", relatedCalculator: "water-intake-calculator", tags: ["health"], category: "health", readingTime: 3 },
  { slugEn: "one-rep-max-guide", slugEs: "guia-repeticion-maxima", slugPt: "guia-repeticao-maxima", titleEn: "One Rep Max Guide", titleEs: "Guia de Repeticion Maxima", titlePt: "Guia de Repeticao Maxima", excerptEn: "Calculate your 1RM.", excerptEs: "Calcula tu 1RM.", excerptPt: "Calcule seu 1RM.", contentEn: "Max weight for one rep. Use our calculator!", contentEs: "Peso maximo para una repeticion. Usa nuestra calculadora!", contentPt: "Peso maximo para uma repeticao. Use nossa calculadora!", relatedCalculator: "one-rep-max-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "sleep-guide", slugEs: "guia-sueno", slugPt: "guia-sono", titleEn: "Sleep Guide", titleEs: "Guia del Sueno", titlePt: "Guia do Sono", excerptEn: "Optimize your sleep.", excerptEs: "Optimiza tu sueno.", excerptPt: "Otimize seu sono.", contentEn: "7-9 hours for adults. Use our calculator!", contentEs: "7-9 horas para adultos. Usa nuestra calculadora!", contentPt: "7-9 horas para adultos. Use nossa calculadora!", relatedCalculator: "sleep-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "running-pace-guide", slugEs: "guia-ritmo-carrera", slugPt: "guia-ritmo-corrida", titleEn: "Running Pace Guide", titleEs: "Guia de Ritmo de Carrera", titlePt: "Guia de Ritmo de Corrida", excerptEn: "Improve your running.", excerptEs: "Mejora tu carrera.", excerptPt: "Melhore sua corrida.", contentEn: "Track pace and predict race times. Use our calculator!", contentEs: "Rastrea ritmo y predice tiempos de carrera. Usa nuestra calculadora!", contentPt: "Rastreie ritmo e preveja tempos de corrida. Use nossa calculadora!", relatedCalculator: "running-pace-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "heart-rate-zones-guide", slugEs: "guia-zonas-fc", slugPt: "guia-zonas-fc", titleEn: "Heart Rate Zones Guide", titleEs: "Guia de Zonas de FC", titlePt: "Guia de Zonas de FC", excerptEn: "Train smarter.", excerptEs: "Entrena mejor.", excerptPt: "Treine melhor.", contentEn: "Know your training zones. Use our calculator!", contentEs: "Conoce tus zonas de entrenamiento. Usa nuestra calculadora!", contentPt: "Conheca suas zonas de treino. Use nossa calculadora!", relatedCalculator: "heart-rate-zones-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "calories-burned-guide", slugEs: "guia-calorias-quemadas", slugPt: "guia-calorias-queimadas", titleEn: "Calories Burned Guide", titleEs: "Guia de Calorias Quemadas", titlePt: "Guia de Calorias Queimadas", excerptEn: "Calculate calories burned.", excerptEs: "Calcula calorias quemadas.", excerptPt: "Calcule calorias queimadas.", contentEn: "By activity type and duration. Use our calculator!", contentEs: "Por tipo de actividad y duracion. Usa nuestra calculadora!", contentPt: "Por tipo de atividade e duracao. Use nossa calculadora!", relatedCalculator: "calories-burned-calculator", tags: ["health"], category: "health", readingTime: 3 },
  { slugEn: "pregnancy-guide", slugEs: "guia-embarazo", slugPt: "guia-gravidez", titleEn: "Pregnancy Guide", titleEs: "Guia de Embarazo", titlePt: "Guia de Gravidez", excerptEn: "Calculate your due date.", excerptEs: "Calcula tu fecha de parto.", excerptPt: "Calcule sua data de parto.", contentEn: "40 weeks from last period. Use our calculator!", contentEs: "40 semanas desde el ultimo periodo. Usa nuestra calculadora!", contentPt: "40 semanas desde a ultima menstruacao. Use nossa calculadora!", relatedCalculator: "pregnancy-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "lean-body-mass-guide", slugEs: "guia-masa-magra", slugPt: "guia-massa-magra", titleEn: "Lean Body Mass Guide", titleEs: "Guia de Masa Magra", titlePt: "Guia de Massa Magra", excerptEn: "Calculate lean mass.", excerptEs: "Calcula masa magra.", excerptPt: "Calcule massa magra.", contentEn: "Total weight minus fat. Use our calculator!", contentEs: "Peso total menos grasa. Usa nuestra calculadora!", contentPt: "Peso total menos gordura. Use nossa calculadora!", relatedCalculator: "lean-body-mass-calculator", tags: ["health"], category: "health", readingTime: 3 },
  { slugEn: "maintenance-calories-guide", slugEs: "guia-calorias-mantenimiento", slugPt: "guia-calorias-manutencao", titleEn: "Maintenance Calories Guide", titleEs: "Guia de Calorias de Mantenimiento", titlePt: "Guia de Calorias de Manutencao", excerptEn: "Find your maintenance calories.", excerptEs: "Encuentra tus calorias de mantenimiento.", excerptPt: "Encontre suas calorias de manutencao.", contentEn: "Calories to maintain weight. Use our calculator!", contentEs: "Calorias para mantener peso. Usa nuestra calculadora!", contentPt: "Calorias para manter peso. Use nossa calculadora!", relatedCalculator: "maintenance-calories-calculator", tags: ["health"], category: "health", readingTime: 3 },
  { slugEn: "calorie-deficit-guide", slugEs: "guia-deficit-calorico", slugPt: "guia-deficit-calorico", titleEn: "Calorie Deficit Guide", titleEs: "Guia de Deficit Calorico", titlePt: "Guia de Deficit Calorico", excerptEn: "Safe weight loss.", excerptEs: "Perdida de peso segura.", excerptPt: "Perda de peso segura.", contentEn: "500 cal deficit for 1 lb/week. Use our calculator!", contentEs: "500 cal de deficit para 0.5 kg/semana. Usa nuestra calculadora!", contentPt: "500 cal de deficit para 0.5 kg/semana. Use nossa calculadora!", relatedCalculator: "calorie-deficit-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "calorie-surplus-guide", slugEs: "guia-superavit-calorico", slugPt: "guia-superavit-calorico", titleEn: "Calorie Surplus Guide", titleEs: "Guia de Superavit Calorico", titlePt: "Guia de Superavit Calorico", excerptEn: "Build muscle.", excerptEs: "Construye musculo.", excerptPt: "Construa musculo.", contentEn: "200-500 cal surplus for muscle. Use our calculator!", contentEs: "200-500 cal de superavit para musculo. Usa nuestra calculadora!", contentPt: "200-500 cal de superavit para musculo. Use nossa calculadora!", relatedCalculator: "calorie-surplus-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "weight-loss-guide", slugEs: "guia-perdida-peso", slugPt: "guia-perda-peso", titleEn: "Weight Loss Guide", titleEs: "Guia de Perdida de Peso", titlePt: "Guia de Perda de Peso", excerptEn: "Lose weight safely.", excerptEs: "Pierde peso de forma segura.", excerptPt: "Perca peso com seguranca.", contentEn: "Deficit plus protein plus exercise. Use our calculator!", contentEs: "Deficit mas proteina mas ejercicio. Usa nuestra calculadora!", contentPt: "Deficit mais proteina mais exercicio. Use nossa calculadora!", relatedCalculator: "weight-loss-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "weight-gain-guide", slugEs: "guia-aumento-peso", slugPt: "guia-ganho-peso", titleEn: "Weight Gain Guide", titleEs: "Guia de Aumento de Peso", titlePt: "Guia de Ganho de Peso", excerptEn: "Gain weight healthily.", excerptEs: "Gana peso saludablemente.", excerptPt: "Ganhe peso de forma saudavel.", contentEn: "Surplus plus protein plus training. Use our calculator!", contentEs: "Superavit mas proteina mas entrenamiento. Usa nuestra calculadora!", contentPt: "Superavit mais proteina mais treino. Use nossa calculadora!", relatedCalculator: "weight-gain-calculator", tags: ["health"], category: "health", readingTime: 4 },
  { slugEn: "tip-calculator-guide", slugEs: "guia-propina", slugPt: "guia-gorjeta", titleEn: "Tip Calculator Guide", titleEs: "Guia de Propina", titlePt: "Guia de Gorjeta", excerptEn: "Calculate tips.", excerptEs: "Calcula propinas.", excerptPt: "Calcule gorjetas.", contentEn: "15-20% is standard. Use our calculator!", contentEs: "15-20% es estandar. Usa nuestra calculadora!", contentPt: "15-20% e padrao. Use nossa calculadora!", relatedCalculator: "tip-calculator", tags: ["everyday"], category: "everyday", readingTime: 3 },
  { slugEn: "discount-guide", slugEs: "guia-descuento", slugPt: "guia-desconto", titleEn: "Discount Calculator Guide", titleEs: "Guia de Descuento", titlePt: "Guia de Desconto", excerptEn: "Calculate discounts.", excerptEs: "Calcula descuentos.", excerptPt: "Calcule descontos.", contentEn: "Original price times discount. Use our calculator!", contentEs: "Precio original por descuento. Usa nuestra calculadora!", contentPt: "Preco original vezes desconto. Use nossa calculadora!", relatedCalculator: "discount-calculator", tags: ["everyday"], category: "everyday", readingTime: 3 },
  { slugEn: "percentage-guide", slugEs: "guia-porcentaje", slugPt: "guia-porcentagem", titleEn: "Percentage Calculator Guide", titleEs: "Guia de Porcentaje", titlePt: "Guia de Porcentagem", excerptEn: "Calculate percentages.", excerptEs: "Calcula porcentajes.", excerptPt: "Calcule porcentagens.", contentEn: "Multiple percentage calculations. Use our calculator!", contentEs: "Multiples calculos de porcentaje. Usa nuestra calculadora!", contentPt: "Multiplos calculos de porcentagem. Use nossa calculadora!", relatedCalculator: "percentage-calculator", tags: ["everyday"], category: "everyday", readingTime: 3 },
  { slugEn: "age-calculator-guide", slugEs: "guia-edad", slugPt: "guia-idade", titleEn: "Age Calculator Guide", titleEs: "Guia de Edad", titlePt: "Guia de Idade", excerptEn: "Calculate your age.", excerptEs: "Calcula tu edad.", excerptPt: "Calcule sua idade.", contentEn: "Exact age in years, months, days. Use our calculator!", contentEs: "Edad exacta en anos, meses, dias. Usa nuestra calculadora!", contentPt: "Idade exata em anos, meses, dias. Use nossa calculadora!", relatedCalculator: "age-calculator", tags: ["everyday"], category: "everyday", readingTime: 2 },
  { slugEn: "date-calculator-guide", slugEs: "guia-fecha", slugPt: "guia-data", titleEn: "Date Calculator Guide", titleEs: "Guia de Fecha", titlePt: "Guia de Data", excerptEn: "Calculate days between dates.", excerptEs: "Calcula dias entre fechas.", excerptPt: "Calcule dias entre datas.", contentEn: "Add or subtract days. Use our calculator!", contentEs: "Suma o resta dias. Usa nuestra calculadora!", contentPt: "Adicione ou subtraia dias. Use nossa calculadora!", relatedCalculator: "date-calculator", tags: ["everyday"], category: "everyday", readingTime: 2 },
  { slugEn: "unit-converter-guide", slugEs: "guia-convertidor", slugPt: "guia-conversor", titleEn: "Unit Converter Guide", titleEs: "Guia de Convertidor", titlePt: "Guia de Conversor", excerptEn: "Convert any unit.", excerptEs: "Convierte cualquier unidad.", excerptPt: "Converta qualquer unidade.", contentEn: "Length, weight, temperature. Use our converter!", contentEs: "Longitud, peso, temperatura. Usa nuestro convertidor!", contentPt: "Comprimento, peso, temperatura. Use nosso conversor!", relatedCalculator: "unit-converter", tags: ["everyday"], category: "everyday", readingTime: 3 },
  { slugEn: "fuel-cost-guide", slugEs: "guia-costo-combustible", slugPt: "guia-custo-combustivel", titleEn: "Fuel Cost Guide", titleEs: "Guia de Costo de Combustible", titlePt: "Guia de Custo de Combustivel", excerptEn: "Calculate fuel costs.", excerptEs: "Calcula costos de combustible.", excerptPt: "Calcule custos de combustivel.", contentEn: "Distance divided by MPG times price. Use our calculator!", contentEs: "Distancia dividida por km/L por precio. Usa nuestra calculadora!", contentPt: "Distancia dividida por km/L vezes preco. Use nossa calculadora!", relatedCalculator: "fuel-cost-calculator", tags: ["everyday"], category: "everyday", readingTime: 3 },
  { slugEn: "time-zone-guide", slugEs: "guia-zona-horaria", slugPt: "guia-fuso-horario", titleEn: "Time Zone Guide", titleEs: "Guia de Zona Horaria", titlePt: "Guia de Fuso Horario", excerptEn: "Convert time zones.", excerptEs: "Convierte zonas horarias.", excerptPt: "Converta fusos horarios.", contentEn: "World time converter. Use our calculator!", contentEs: "Convertidor de hora mundial. Usa nuestra calculadora!", contentPt: "Conversor de hora mundial. Use nossa calculadora!", relatedCalculator: "time-zone-calculator", tags: ["everyday"], category: "everyday", readingTime: 2 },
  { slugEn: "gpa-guide", slugEs: "guia-promedio", slugPt: "guia-media", titleEn: "GPA Calculator Guide", titleEs: "Guia de Promedio", titlePt: "Guia de Media", excerptEn: "Calculate your GPA.", excerptEs: "Calcula tu promedio.", excerptPt: "Calcule sua media.", contentEn: "Grade points times credits. Use our calculator!", contentEs: "Puntos de calificacion por creditos. Usa nuestra calculadora!", contentPt: "Pontos de nota vezes creditos. Use nossa calculadora!", relatedCalculator: "gpa-calculator", tags: ["everyday"], category: "everyday", readingTime: 3 },
  { slugEn: "random-number-guide", slugEs: "guia-numero-aleatorio", slugPt: "guia-numero-aleatorio", titleEn: "Random Number Guide", titleEs: "Guia de Numero Aleatorio", titlePt: "Guia de Numero Aleatorio", excerptEn: "Generate random numbers.", excerptEs: "Genera numeros aleatorios.", excerptPt: "Gere numeros aleatorios.", contentEn: "For games, lottery, statistics. Use our generator!", contentEs: "Para juegos, loteria, estadisticas. Usa nuestro generador!", contentPt: "Para jogos, loteria, estatisticas. Use nosso gerador!", relatedCalculator: "random-number-generator", tags: ["everyday"], category: "everyday", readingTime: 2 },
];

async function main() {
  console.log("Starting seed...");
  const categories = [
    { slug: "finance", nameEn: "Finance", nameEs: "Finanzas", namePt: "Financas", color: "blue", icon: "money" },
    { slug: "health", nameEn: "Health", nameEs: "Salud", namePt: "Saude", color: "green", icon: "heart" },
    { slug: "everyday", nameEn: "Everyday", nameEs: "Cotidiano", namePt: "Cotidiano", color: "purple", icon: "calc" },
  ];
  for (const cat of categories) {
    await prisma.blogCategory.upsert({ where: { slug: cat.slug }, update: {}, create: cat });
  }
  const finCat = await prisma.blogCategory.findUnique({ where: { slug: "finance" } });
  const healthCat = await prisma.blogCategory.findUnique({ where: { slug: "health" } });
  const everyCat = await prisma.blogCategory.findUnique({ where: { slug: "everyday" } });
  const catMap: Record<string, string | null> = { finance: finCat?.id || null, health: healthCat?.id || null, everyday: everyCat?.id || null };
  let created = 0;
  for (const p of blogPosts) {
    try {
      await prisma.post.create({
        data: {
          slugEn: p.slugEn, slugEs: p.slugEs, slugPt: p.slugPt,
          titleEn: p.titleEn, titleEs: p.titleEs, titlePt: p.titlePt,
          excerptEn: p.excerptEn, excerptEs: p.excerptEs, excerptPt: p.excerptPt,
          contentEn: p.contentEn, contentEs: p.contentEs, contentPt: p.contentPt,
          metaTitleEn: p.titleEn + " | Kalcufy", metaTitleEs: p.titleEs + " | Kalcufy", metaTitlePt: p.titlePt + " | Kalcufy",
          metaDescriptionEn: p.excerptEn, metaDescriptionEs: p.excerptEs, metaDescriptionPt: p.excerptPt,
          relatedCalculator: p.relatedCalculator, tags: p.tags, categoryId: catMap[p.category],
          status: "PUBLISHED", publishedAt: new Date(), readingTime: p.readingTime, views: Math.floor(Math.random() * 500) + 50,
        },
      });
      created++;
      console.log(created + ". " + p.titleEn);
    } catch (e: any) { console.error("Error: " + p.slugEn); }
  }
  console.log("Done! Created " + created + " posts.");
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(async () => { await prisma.$disconnect(); });
