"use client";

import { useState } from "react";

/**
 * EXPORT UTILS V4
 * 
 * Export calculator results to PDF and CSV
 * Currently free - can add paywall later with isPro check
 */

// ─────────────────────────────────────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────────────────────────────────────
interface ExportData {
  calculatorName: string;
  calculatorSlug: string;
  date: string;
  locale: string;
  inputs: Array<{ label: string; value: string; }>;
  results: Array<{ label: string; value: string; isPrimary?: boolean; }>;
  summary?: string;
}

interface ExportOptions {
  isPro?: boolean; // For future paywall
  includeDisclaimer?: boolean;
  brandingEnabled?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// TRANSLATIONS
// ─────────────────────────────────────────────────────────────────────────────
const PDF_TRANSLATIONS = {
  en: {
    inputs: "Input Values",
    results: "Results", 
    summary: "Summary",
    field: "Field",
    value: "Value",
    metric: "Metric",
    footer1: "Generated by Kalcufy.com",
    footer2: "This is an estimate only. Consult a professional.",
  },
  es: {
    inputs: "Valores de Entrada",
    results: "Resultados",
    summary: "Resumen",
    field: "Campo",
    value: "Valor",
    metric: "Metrica",
    footer1: "Generado por Kalcufy.com",
    footer2: "Esto es solo una estimacion. Consulte a un profesional.",
  },
  pt: {
    inputs: "Valores de Entrada",
    results: "Resultados",
    summary: "Resumo",
    field: "Campo",
    value: "Valor",
    metric: "Metrica",
    footer1: "Gerado por Kalcufy.com",
    footer2: "Esta e apenas uma estimativa. Consulte um profissional.",
  },
  fr: {
    inputs: "Valeurs d'Entree",
    results: "Resultats",
    summary: "Resume",
    field: "Champ",
    value: "Valeur",
    metric: "Metrique",
    footer1: "Genere par Kalcufy.com",
    footer2: "Ceci est une estimation uniquement. Consultez un professionnel.",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// CSV EXPORT
// ─────────────────────────────────────────────────────────────────────────────
export function exportToCSV(data: ExportData, _options: ExportOptions = {}) {
  const t = PDF_TRANSLATIONS[data.locale as keyof typeof PDF_TRANSLATIONS] || PDF_TRANSLATIONS.en;
  const rows: string[][] = [];
  
  // Header
  rows.push(["Kalcufy.com - " + data.calculatorName]);
  rows.push(["Date", data.date]);
  rows.push([]);
  
  // Inputs section
  rows.push([t.inputs.toUpperCase()]);
  rows.push([t.field, t.value]);
  data.inputs.forEach(input => {
    rows.push([input.label, input.value]);
  });
  rows.push([]);
  
  // Results section
  rows.push([t.results.toUpperCase()]);
  rows.push([t.metric, t.value]);
  data.results.forEach(result => {
    rows.push([result.label, result.value]);
  });
  
  // Summary
  if (data.summary) {
    rows.push([]);
    rows.push([t.summary.toUpperCase()]);
    rows.push([data.summary]);
  }
  
  // Disclaimer
  rows.push([]);
  rows.push(["---"]);
  rows.push([t.footer1]);
  rows.push([t.footer2]);
  
  // Convert to CSV string
  const csvContent = rows
    .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\n");
  
  // Download
  const blob = new Blob(["\ufeff" + csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${data.calculatorSlug}-${data.date}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// ─────────────────────────────────────────────────────────────────────────────
// PDF EXPORT
// ─────────────────────────────────────────────────────────────────────────────
export async function exportToPDF(data: ExportData, _options: ExportOptions = {}) {
  const { jsPDF } = await import("jspdf");
  const t = PDF_TRANSLATIONS[data.locale as keyof typeof PDF_TRANSLATIONS] || PDF_TRANSLATIONS.en;
  
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;
  
  // Colors
  const primaryColor: [number, number, number] = [59, 130, 246]; // Blue-500
  const textColor: [number, number, number] = [30, 41, 59]; // Slate-800
  const mutedColor: [number, number, number] = [100, 116, 139]; // Slate-500
  const bgColor: [number, number, number] = [248, 250, 252]; // Slate-50
  
  // ─────────────────────────────────────────────────────────────────────────
  // HEADER - Blue bar with Kalcufy branding
  // ─────────────────────────────────────────────────────────────────────────
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 40, "F");
  
  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("Kalcufy", margin, 18);
  
  // Tagline
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Free Online Calculators", margin, 26);
  
  // Calculator name
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(data.calculatorName, margin, 35);
  
  // Date (right aligned)
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(data.date, pageWidth - margin, 35, { align: "right" });
  
  y = 55;
  
  // ─────────────────────────────────────────────────────────────────────────
  // PRIMARY RESULT - Big highlight box
  // ─────────────────────────────────────────────────────────────────────────
  const primaryResult = data.results.find(r => r.isPrimary);
  if (primaryResult) {
    // Background box
    doc.setFillColor(239, 246, 255); // Blue-50
    doc.roundedRect(margin, y, contentWidth, 35, 4, 4, "F");
    
    // Border
    doc.setDrawColor(...primaryColor);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentWidth, 35, 4, 4, "S");
    
    // Label
    doc.setTextColor(...mutedColor);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(primaryResult.label, margin + 10, y + 12);
    
    // Value
    doc.setTextColor(...primaryColor);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(primaryResult.value, margin + 10, y + 27);
    
    y += 45;
  }
  
  // ─────────────────────────────────────────────────────────────────────────
  // INPUTS SECTION
  // ─────────────────────────────────────────────────────────────────────────
  doc.setTextColor(...textColor);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(t.inputs, margin, y);
  y += 8;
  
  // Table header
  doc.setFillColor(241, 245, 249); // Slate-100
  doc.rect(margin, y, contentWidth, 8, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...mutedColor);
  doc.text(t.field, margin + 5, y + 5.5);
  doc.text(t.value, margin + contentWidth - 50, y + 5.5);
  y += 10;
  
  // Table rows
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...textColor);
  data.inputs.forEach((input, index) => {
    if (index % 2 === 0) {
      doc.setFillColor(...bgColor);
      doc.rect(margin, y - 2, contentWidth, 7, "F");
    }
    doc.setFontSize(9);
    doc.text(truncateText(input.label, 50), margin + 5, y + 3);
    doc.setFont("helvetica", "bold");
    doc.text(truncateText(String(input.value), 30), margin + contentWidth - 50, y + 3);
    doc.setFont("helvetica", "normal");
    y += 7;
  });
  
  y += 12;
  
  // ─────────────────────────────────────────────────────────────────────────
  // RESULTS SECTION
  // ─────────────────────────────────────────────────────────────────────────
  doc.setTextColor(...textColor);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(t.results, margin, y);
  y += 8;
  
  // Table header
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, contentWidth, 8, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...mutedColor);
  doc.text(t.metric, margin + 5, y + 5.5);
  doc.text(t.value, margin + contentWidth - 50, y + 5.5);
  y += 10;
  
  // Table rows (excluding primary)
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...textColor);
  const secondaryResults = data.results.filter(r => !r.isPrimary);
  secondaryResults.forEach((result, index) => {
    if (index % 2 === 0) {
      doc.setFillColor(...bgColor);
      doc.rect(margin, y - 2, contentWidth, 7, "F");
    }
    doc.setFontSize(9);
    doc.text(truncateText(result.label, 50), margin + 5, y + 3);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...primaryColor);
    doc.text(truncateText(result.value, 30), margin + contentWidth - 50, y + 3);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...textColor);
    y += 7;
  });
  
  y += 12;
  
  // ─────────────────────────────────────────────────────────────────────────
  // SUMMARY
  // ─────────────────────────────────────────────────────────────────────────
  if (data.summary) {
    doc.setTextColor(...textColor);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(t.summary, margin, y);
    y += 8;
    
    doc.setFillColor(239, 246, 255); // Blue-50
    const summaryLines = doc.splitTextToSize(data.summary, contentWidth - 16);
    const summaryHeight = Math.max(20, summaryLines.length * 5 + 10);
    doc.roundedRect(margin, y, contentWidth, summaryHeight, 3, 3, "F");
    
    doc.setTextColor(30, 64, 175); // Blue-800
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(summaryLines, margin + 8, y + 8);
    
    y += summaryHeight + 10;
  }
  
  // ─────────────────────────────────────────────────────────────────────────
  // FOOTER
  // ─────────────────────────────────────────────────────────────────────────
  const footerY = doc.internal.pageSize.getHeight() - 20;
  
  // Divider line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(margin, footerY - 8, pageWidth - margin, footerY - 8);
  
  // Footer text
  doc.setTextColor(...mutedColor);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(t.footer1, margin, footerY - 2);
  doc.text(t.footer2, margin, footerY + 3);
  
  // Website link
  doc.setTextColor(...primaryColor);
  doc.setFont("helvetica", "bold");
  doc.textWithLink("www.kalcufy.com", pageWidth - margin - 28, footerY, { url: "https://www.kalcufy.com" });
  
  // ─────────────────────────────────────────────────────────────────────────
  // SAVE
  // ─────────────────────────────────────────────────────────────────────────
  doc.save(`${data.calculatorSlug}-${data.date}.pdf`);
}

// Helper function
function truncateText(text: string, maxLength: number): string {
  if (!text) return "";
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength - 3) + "...";
}

// ─────────────────────────────────────────────────────────────────────────────
// LOADING SPINNER
// ─────────────────────────────────────────────────────────────────────────────
function LoadingSpinner() {
  return (
    <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
    </svg>
  );
}
